server:
  port: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "abstract_factory_db"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "abstract_factory_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: 30s

kafka:
  brokers:
    - "localhost:9092"
  group_id: "abstract-factory-group"
  topic: "abstract-factory-events"
  consumer_timeout: 10s
  producer_timeout: 10s

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  write_wait: 10s

abstract_factory:
  name: "Abstract Factory Service"
  version: "1.0.0"
  description: "Abstract Factory pattern service for creating families of related objects"
  max_factories: 100
  max_products: 1000
  cleanup_interval: "1h"
  validation_enabled: true
  caching_enabled: true
  monitoring_enabled: true
  auditing_enabled: true
  supported_factory_types:
    - "ConcreteFactory1"
    - "ConcreteFactory2"
    - "PaymentFactory"
    - "OrderFactory"
    - "UserFactory"
    - "NotificationFactory"
  supported_product_types:
    - "ProductA"
    - "ProductB"
    - "ProductC"
    - "PaymentProduct"
    - "OrderProduct"
    - "UserProduct"
    - "NotificationProduct"
  validation_rules:
    factory:
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      version:
        required: true
        format: "semver"
    product:
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      price:
        required: true
        min: 0.01
        max: 1000000
  metadata:
    environment: "development"
    region: "us-east-1"
    team: "backend"
    project: "abstract-factory-service"
