name: "Mediator Service"
version: "1.0.0"
description: "Mediator pattern implementation with microservice architecture"

# Mediator Configuration
max_mediators: 100
max_colleagues: 1000
timeout: "30m"
retry_count: 3
types:
  - "message"
  - "event"
  - "command"
  - "query"
  - "notification"
  - "workflow"
  - "service"
  - "resource"
  - "task"
  - "job"

# Database Configuration
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "mediator_db"
    max_connections: 100
    max_idle_connections: 10
    connection_max_lifetime: "1h"
  
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "mediator_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: "30m"
  
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    max_retries: 3
    pool_size: 10
    min_idle_connections: 5

# Cache Configuration
cache:
  enabled: true
  type: "memory"
  ttl: "5m"
  max_size: 1000
  cleanup_interval: "10m"
  eviction_policy: "lru"

# Message Queue Configuration
message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "mediator-events"
    - "mediator-commands"
    - "mediator-responses"
  consumer_group: "mediator-service"
  auto_commit: true
  commit_interval: "1s"

# WebSocket Configuration
websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: "10s"
  ping_period: "54s"
  pong_wait: "60s"
  write_wait: "10s"
  max_message_size: 512
  max_connections: 1000

# Security Configuration
security:
  enabled: true
  jwt_secret: "your-secret-key"
  token_expiry: "24h"
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: "1m"
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Monitoring Configuration
monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: "30s"
  health_check_interval: "10s"
  metrics_retention: "24h"
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 80
    disk_usage: 90
    response_time: "1s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "/var/log/mediator-service.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Performance Configuration
performance:
  max_concurrent_requests: 1000
  request_timeout: "30s"
  connection_timeout: "10s"
  keep_alive: true
  keep_alive_timeout: "30s"
  max_idle_connections: 100
  idle_connection_timeout: "90s"

# Mediator Specific Configuration
mediator:
  default_mediator_type: "message"
  max_mediators_per_type: 10
  mediator_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"
  parallel_processing: true
  max_workers: 10
  worker_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2

# Colleague Configuration
colleagues:
  default_type: "service"
  max_colleagues_per_mediator: 100
  colleague_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"
  health_check_interval: "30s"
  inactive_timeout: "5m"

# Message Configuration
messages:
  enabled: true
  max_messages: 10000
  message_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  priority_levels:
    - "low"
    - "normal"
    - "high"
    - "urgent"

# Event Configuration
events:
  enabled: true
  max_events: 10000
  event_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  event_types:
    - "system"
    - "user"
    - "application"
    - "error"

# Command Configuration
commands:
  enabled: true
  max_commands: 10000
  command_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  command_types:
    - "create"
    - "update"
    - "delete"
    - "execute"

# Query Configuration
queries:
  enabled: true
  max_queries: 10000
  query_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  query_types:
    - "select"
    - "count"
    - "aggregate"
    - "search"

# Notification Configuration
notifications:
  enabled: true
  max_notifications: 10000
  notification_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  notification_types:
    - "email"
    - "sms"
    - "push"
    - "in-app"

# Workflow Configuration
workflows:
  enabled: true
  max_workflows: 1000
  workflow_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  workflow_types:
    - "sequential"
    - "parallel"
    - "conditional"
    - "loop"

# Service Configuration
services:
  enabled: true
  max_services: 1000
  service_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  service_types:
    - "microservice"
    - "api"
    - "database"
    - "cache"

# Resource Configuration
resources:
  enabled: true
  max_resources: 1000
  resource_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  resource_types:
    - "cpu"
    - "memory"
    - "disk"
    - "network"

# Task Configuration
tasks:
  enabled: true
  max_tasks: 10000
  task_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  task_types:
    - "computation"
    - "io"
    - "network"
    - "database"

# Job Configuration
jobs:
  enabled: true
  max_jobs: 1000
  job_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  job_types:
    - "scheduled"
    - "on-demand"
    - "recurring"
    - "one-time"

# Statistics Configuration
statistics:
  enabled: true
  collect_interval: "1m"
  retention_period: "7d"
  metrics:
    - "total_mediators"
    - "active_mediators"
    - "total_colleagues"
    - "active_colleagues"
    - "total_messages"
    - "successful_messages"
    - "failed_messages"
    - "average_latency"
    - "error_rate"

# Audit Configuration
audit:
  enabled: true
  log_level: "info"
  log_operations:
    - "create"
    - "read"
    - "update"
    - "delete"
    - "send"
    - "broadcast"
  retention_period: "30d"
  max_log_size: 1000

# Development Configuration
development:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060

# Production Configuration
production:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060
  graceful_shutdown_timeout: "30s"
  health_check_timeout: "5s"
