name: "Memento Service"
version: "1.0.0"
description: "Memento pattern implementation with microservice architecture"

# Memento Configuration
max_mementos: 10000
max_memento_size: 1048576  # 1MB
max_memento_age: "24h"
cleanup_interval: "1h"
backup_interval: "6h"
replication_interval: "1h"
validation_interval: "30m"
compression_enabled: true
encryption_enabled: true
caching_enabled: true
indexing_enabled: true
monitoring_enabled: true
auditing_enabled: true
scheduling_enabled: true
backup_enabled: true
replication_enabled: true
validation_enabled: true

# Supported Formats
supported_formats:
  - "json"
  - "xml"
  - "yaml"
  - "protobuf"
  - "msgpack"

default_format: "json"

# Supported Algorithms
supported_algorithms:
  - "gzip"
  - "lz4"
  - "snappy"
  - "zstd"
  - "brotli"

default_algorithm: "gzip"

# Validation Rules
validation_rules:
  max_size: 1048576  # 1MB
  max_age: "24h"
  max_metadata_size: 1024  # 1KB
  required_fields:
    - "id"
    - "originator_id"
    - "state"
    - "timestamp"
  allowed_types:
    - "document"
    - "database"
    - "file"
    - "configuration"
    - "user"
    - "session"

# Database Configuration
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "memento_db"
    max_connections: 100
    max_idle_connections: 10
    connection_max_lifetime: "1h"
  
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "memento_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: "30m"
  
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    max_retries: 3
    pool_size: 10
    min_idle_connections: 5

# Cache Configuration
cache:
  enabled: true
  type: "memory"
  ttl: "5m"
  max_size: 1000
  cleanup_interval: "10m"
  eviction_policy: "lru"

# Message Queue Configuration
message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "memento-events"
    - "memento-commands"
    - "memento-responses"
  consumer_group: "memento-service"
  auto_commit: true
  commit_interval: "1s"

# WebSocket Configuration
websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: "10s"
  ping_period: "54s"
  pong_wait: "60s"
  write_wait: "10s"
  max_message_size: 512
  max_connections: 1000

# Security Configuration
security:
  enabled: true
  jwt_secret: "your-secret-key"
  token_expiry: "24h"
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: "1m"
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Monitoring Configuration
monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: "30s"
  health_check_interval: "10s"
  metrics_retention: "24h"
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 80
    disk_usage: 90
    response_time: "1s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "/var/log/memento-service.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Performance Configuration
performance:
  max_concurrent_requests: 1000
  request_timeout: "30s"
  connection_timeout: "10s"
  keep_alive: true
  keep_alive_timeout: "30s"
  max_idle_connections: 100
  idle_connection_timeout: "90s"

# Memento Specific Configuration
memento:
  default_memento_type: "document"
  max_mementos_per_caretaker: 1000
  memento_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"
  parallel_processing: true
  max_workers: 10
  worker_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2

# Caretaker Configuration
caretakers:
  default_type: "memory"
  max_caretakers: 100
  caretaker_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"
  health_check_interval: "30s"
  inactive_timeout: "5m"

# Originator Configuration
originators:
  default_type: "document"
  max_originators: 1000
  originator_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"
  health_check_interval: "30s"
  inactive_timeout: "5m"

# Serialization Configuration
serialization:
  enabled: true
  max_serialization_size: 10485760  # 10MB
  serialization_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  supported_formats:
    - "json"
    - "xml"
    - "yaml"
    - "protobuf"
    - "msgpack"

# Compression Configuration
compression:
  enabled: true
  max_compression_size: 10485760  # 10MB
  compression_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  supported_algorithms:
    - "gzip"
    - "lz4"
    - "snappy"
    - "zstd"
    - "brotli"

# Encryption Configuration
encryption:
  enabled: true
  max_encryption_size: 10485760  # 10MB
  encryption_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  supported_algorithms:
    - "aes-256-gcm"
    - "aes-256-cbc"
    - "chacha20-poly1305"

# Validation Configuration
validation:
  enabled: true
  max_validation_size: 10485760  # 10MB
  validation_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  validation_rules:
    max_size: 1048576  # 1MB
    max_age: "24h"
    max_metadata_size: 1024  # 1KB
    required_fields:
      - "id"
      - "originator_id"
      - "state"
      - "timestamp"
    allowed_types:
      - "document"
      - "database"
      - "file"
      - "configuration"
      - "user"
      - "session"

# Indexing Configuration
indexing:
  enabled: true
  max_index_size: 10485760  # 10MB
  index_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  index_types:
    - "fulltext"
    - "keyword"
    - "numeric"
    - "date"
    - "boolean"

# Backup Configuration
backup:
  enabled: true
  max_backup_size: 1073741824  # 1GB
  backup_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  backup_types:
    - "full"
    - "incremental"
    - "differential"
  backup_storage:
    - "local"
    - "s3"
    - "gcs"
    - "azure"

# Replication Configuration
replication:
  enabled: true
  max_replication_size: 1073741824  # 1GB
  replication_timeout: "1h"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2
  replication_types:
    - "synchronous"
    - "asynchronous"
    - "semi-synchronous"
  replication_targets:
    - "localhost:8081"
    - "localhost:8082"
    - "localhost:8083"

# Statistics Configuration
statistics:
  enabled: true
  collect_interval: "1m"
  retention_period: "7d"
  metrics:
    - "total_mementos"
    - "active_mementos"
    - "total_size"
    - "average_size"
    - "max_size"
    - "min_size"
    - "total_operations"
    - "successful_operations"
    - "failed_operations"
    - "average_latency"
    - "error_rate"

# Audit Configuration
audit:
  enabled: true
  log_level: "info"
  log_operations:
    - "create"
    - "read"
    - "update"
    - "delete"
    - "backup"
    - "restore"
    - "replicate"
  retention_period: "30d"
  max_log_size: 1000

# Development Configuration
development:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060

# Production Configuration
production:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060
  graceful_shutdown_timeout: "30s"
  health_check_timeout: "5s"
