name: "Iterator Service"
version: "1.0.0"
description: "Iterator pattern implementation with microservice architecture"

# Iterator Configuration
max_iterators: 1000
timeout: "30m"
retry_count: 3
types:
  - "slice"
  - "map"
  - "channel"
  - "database"
  - "file"
  - "filtered"
  - "sorted"
  - "transformed"

# Database Configuration
database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "iterator_db"
    max_connections: 100
    max_idle_connections: 10
    connection_max_lifetime: "1h"
  
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "iterator_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: "30m"
  
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    max_retries: 3
    pool_size: 10
    min_idle_connections: 5

# Cache Configuration
cache:
  enabled: true
  type: "memory"
  ttl: "5m"
  max_size: 1000
  cleanup_interval: "10m"
  eviction_policy: "lru"

# Message Queue Configuration
message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "iterator-events"
    - "iterator-commands"
    - "iterator-responses"
  consumer_group: "iterator-service"
  auto_commit: true
  commit_interval: "1s"

# WebSocket Configuration
websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: "10s"
  ping_period: "54s"
  pong_wait: "60s"
  write_wait: "10s"
  max_message_size: 512
  max_connections: 1000

# Security Configuration
security:
  enabled: true
  jwt_secret: "your-secret-key"
  token_expiry: "24h"
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: "1m"
  cors_enabled: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Monitoring Configuration
monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: "30s"
  health_check_interval: "10s"
  metrics_retention: "24h"
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 80
    disk_usage: 90
    response_time: "1s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "/var/log/iterator-service.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

# Performance Configuration
performance:
  max_concurrent_requests: 1000
  request_timeout: "30s"
  connection_timeout: "10s"
  keep_alive: true
  keep_alive_timeout: "30s"
  max_idle_connections: 100
  idle_connection_timeout: "90s"

# Iterator Specific Configuration
iterator:
  default_batch_size: 100
  max_batch_size: 1000
  min_batch_size: 1
  batch_timeout: "5s"
  parallel_processing: true
  max_workers: 10
  worker_timeout: "30s"
  retry_policy:
    max_retries: 3
    initial_delay: "1s"
    max_delay: "30s"
    backoff_multiplier: 2

# Collection Configuration
collections:
  default_type: "slice"
  max_collections: 100
  collection_timeout: "1h"
  auto_cleanup: true
  cleanup_interval: "10m"

# Filter Configuration
filters:
  enabled: true
  max_filters: 100
  filter_timeout: "30s"
  cache_filters: true
  filter_cache_ttl: "5m"

# Sort Configuration
sorters:
  enabled: true
  max_sorters: 100
  sort_timeout: "30s"
  cache_sorts: true
  sort_cache_ttl: "5m"

# Transform Configuration
transformers:
  enabled: true
  max_transformers: 100
  transform_timeout: "30s"
  cache_transforms: true
  transform_cache_ttl: "5m"

# Statistics Configuration
statistics:
  enabled: true
  collect_interval: "1m"
  retention_period: "7d"
  metrics:
    - "total_iterators"
    - "active_iterators"
    - "total_items"
    - "processed_items"
    - "average_latency"
    - "error_rate"

# Audit Configuration
audit:
  enabled: true
  log_level: "info"
  log_operations:
    - "create"
    - "read"
    - "update"
    - "delete"
    - "iterate"
  retention_period: "30d"
  max_log_size: 1000

# Development Configuration
development:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060

# Production Configuration
production:
  debug: false
  hot_reload: false
  mock_services: false
  test_mode: false
  profiling_enabled: false
  profiling_port: 6060
  graceful_shutdown_timeout: "30s"
  health_check_timeout: "5s"
