server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "decorator_db"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s

  mongodb:
    uri: "mongodb://localhost:27017"
    database: "decorator_db"
    timeout: 30s
    max_pool_size: 100
    min_pool_size: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

kafka:
  brokers:
    - "localhost:9092"
  producer:
    retry_max: 3
    retry_backoff: 100ms
    required_acks: 1
    compression: "snappy"
  consumer:
    group_id: "decorator-service"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    auto_commit_interval: 1s

components:
  payment:
    name: "payment"
    description: "Handles payment processing"
    enabled: true
    timeout: 30s
    retry_count: 3

  notification:
    name: "notification"
    description: "Handles notification sending"
    enabled: true
    timeout: 30s
    retry_count: 3

  user:
    name: "user"
    description: "Handles user management"
    enabled: true
    timeout: 30s
    retry_count: 3

  order:
    name: "order"
    description: "Handles order management"
    enabled: true
    timeout: 30s
    retry_count: 3

  inventory:
    name: "inventory"
    description: "Handles inventory management"
    enabled: true
    timeout: 30s
    retry_count: 3

  analytics:
    name: "analytics"
    description: "Handles analytics processing"
    enabled: true
    timeout: 30s
    retry_count: 3

  audit:
    name: "audit"
    description: "Handles audit logging"
    enabled: true
    timeout: 30s
    retry_count: 3

decorators:
  logging:
    name: "logging"
    description: "Adds logging functionality"
    enabled: true
    level: "info"
    format: "json"
    include_data: true

  metrics:
    name: "metrics"
    description: "Adds metrics collection"
    enabled: true
    port: 9090
    path: "/metrics"
    collect_interval: 30s

  cache:
    name: "cache"
    description: "Adds caching functionality"
    enabled: true
    type: "memory"
    ttl: 5m
    max_size: 1000
    compression: true

  security:
    name: "security"
    description: "Adds security functionality"
    enabled: true
    validate_input: true
    sanitize_input: true
    check_permissions: true
    audit_logging: true

  rate_limit:
    name: "rate_limit"
    description: "Adds rate limiting functionality"
    enabled: true
    requests_per_minute: 100
    burst_size: 20
    window_size: 1m

  circuit_breaker:
    name: "circuit_breaker"
    description: "Adds circuit breaker functionality"
    enabled: true
    failure_threshold: 5
    success_threshold: 3
    timeout: 30s
    max_requests: 10

  retry:
    name: "retry"
    description: "Adds retry functionality"
    enabled: true
    max_attempts: 3
    initial_delay: 100ms
    max_delay: 5s
    backoff_factor: 2.0

  monitoring:
    name: "monitoring"
    description: "Adds monitoring functionality"
    enabled: true
    port: 9090
    log_level: "info"
    collect_interval: 30s

  validation:
    name: "validation"
    description: "Adds validation functionality"
    enabled: true
    strict_mode: false
    rules: {}

  encryption:
    name: "encryption"
    description: "Adds encryption functionality"
    enabled: true
    algorithm: "AES-256-GCM"
    key_size: 32
    salt_length: 16
    iterations: 10000

  compression:
    name: "compression"
    description: "Adds compression functionality"
    enabled: true
    algorithm: "gzip"
    level: 6
    min_size: 1024

  serialization:
    name: "serialization"
    description: "Adds serialization functionality"
    enabled: true
    format: "json"
    compression: true
    encryption: false

  notification:
    name: "notification"
    description: "Adds notification functionality"
    enabled: true
    channels: ["email", "sms", "push"]
    retry_count: 3
    retry_delay: 1s
    batch_size: 100

  analytics:
    name: "analytics"
    description: "Adds analytics functionality"
    enabled: true
    events: ["request", "response", "error"]
    batch_size: 1000
    flush_interval: 30s

  audit:
    name: "audit"
    description: "Adds audit functionality"
    enabled: true
    events: ["create", "update", "delete", "read"]
    retention: 90d
    compression: true

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false
    path: "logs/decorator.log"
    max_size: 100
    max_backups: 3
    max_age: 28

websocket:
  enabled: true
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  max_message_size: 512

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

health_check:
  enabled: true
  interval: 30s
  timeout: 5s
  retry_count: 3

decorator:
  name: "decorator-service"
  version: "1.0.0"
  description: "Decorator Pattern Implementation Service"
  timeout: 30s
  max_retries: 3
  retry_delay: 1s
  enable_compression: true
  enable_cors: true
  enable_metrics: true
  enable_tracing: false

security:
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    headers:
      - "Content-Type"
      - "Authorization"
    credentials: true

  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20

  api_key:
    enabled: false
    header_name: "X-API-Key"
    required_endpoints:
      - "/api/v1/components"
      - "/api/v1/decorators"
      - "/api/v1/management"
