server:
  port: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "saga_db"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "saga_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: 30s

kafka:
  brokers:
    - "localhost:9092"
  group_id: "saga-group"
  topic: "saga-events"
  consumer_timeout: 10s
  producer_timeout: 10s

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  write_wait: 10s

saga:
  name: "Saga Service"
  version: "1.0.0"
  description: "Saga pattern service for managing distributed transactions"
  max_sagas: 1000
  max_steps: 10000
  cleanup_interval: "1h"
  validation_enabled: true
  caching_enabled: true
  monitoring_enabled: true
  auditing_enabled: true
  retry_enabled: true
  compensation_enabled: true
  supported_saga_types:
    - "PaymentSaga"
    - "OrderSaga"
    - "UserSaga"
    - "NotificationSaga"
    - "InventorySaga"
    - "ShippingSaga"
  supported_step_types:
    - "PaymentStep"
    - "OrderStep"
    - "UserStep"
    - "NotificationStep"
    - "InventoryStep"
    - "ShippingStep"
  validation_rules:
    saga:
      id:
        required: true
        min_length: 2
        max_length: 100
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      version:
        required: true
        format: "semver"
    step:
      id:
        required: true
        min_length: 2
        max_length: 100
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      action:
        required: true
        min_length: 2
        max_length: 100
      compensation:
        required: true
        min_length: 2
        max_length: 100
      max_retries:
        required: true
        min: 0
        max: 10
      timeout:
        required: true
        min: "1s"
        max: "1h"
  metadata:
    environment: "development"
    region: "us-east-1"
    team: "backend"
    project: "saga-service"
