server:
  port: ":8080"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "builder_db"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "builder_db"
    max_pool_size: 100
    min_pool_size: 10
    max_idle_time: 30s

kafka:
  brokers:
    - "localhost:9092"
  group_id: "builder-group"
  topic: "builder-events"
  consumer_timeout: 10s
  producer_timeout: 10s

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  write_wait: 10s

builder:
  name: "Builder Service"
  version: "1.0.0"
  description: "Builder pattern service for constructing complex objects step by step"
  max_builders: 100
  max_products: 1000
  max_directors: 50
  cleanup_interval: "1h"
  validation_enabled: true
  caching_enabled: true
  monitoring_enabled: true
  auditing_enabled: true
  supported_builder_types:
    - "ConcreteBuilder"
    - "PaymentBuilder"
    - "OrderBuilder"
    - "UserBuilder"
    - "NotificationBuilder"
    - "ReportBuilder"
  supported_product_types:
    - "ConcreteProduct"
    - "PaymentProduct"
    - "OrderProduct"
    - "UserProduct"
    - "NotificationProduct"
    - "ReportProduct"
  validation_rules:
    builder:
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      version:
        required: true
        format: "semver"
    product:
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      price:
        required: true
        min: 0.01
        max: 1000000
      category:
        required: true
        min_length: 2
        max_length: 50
    director:
      name:
        required: true
        min_length: 2
        max_length: 100
      description:
        required: true
        min_length: 10
        max_length: 500
      version:
        required: true
        format: "semver"
  metadata:
    environment: "development"
    region: "us-east-1"
    team: "backend"
    project: "builder-service"
