server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 3306
  username: root
  password: password
  database: adapter_db
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

mongodb:
  uri: mongodb://localhost:27017
  database: adapter_db
  max_pool_size: 100
  min_pool_size: 10
  max_idle_time: 30m

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

kafka:
  brokers: ["localhost:9092"]
  topics:
    adapter_events: adapter-events
    adapter_metrics: adapter-metrics
  producer:
    batch_size: 100
    batch_timeout: 10ms
    compression: gzip
  consumer:
    group_id: adapter-service
    auto_offset_reset: earliest
    max_wait_time: 1s

adapter:
  default_timeout: 30s
  max_retries: 3
  retry_delay: 1s
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30s
    half_open_max_calls: 3
  adapters:
    payment_gateway:
      default_adapter: "stripe"
      adapters:
        stripe:
          enabled: true
          priority: 1
          timeout: 5s
          retry_count: 3
          parameters:
            api_key: "sk_test_..."
            webhook_secret: "whsec_..."
          fallback: "razorpay"
        razorpay:
          enabled: true
          priority: 2
          timeout: 5s
          retry_count: 3
          parameters:
            api_key: "rzp_test_..."
            api_secret: "rzp_test_..."
          fallback: "paypal"
        paypal:
          enabled: true
          priority: 3
          timeout: 5s
          retry_count: 3
          parameters:
            client_id: "paypal_client_id"
            client_secret: "paypal_client_secret"
          fallback: "bank_transfer"
        bank_transfer:
          enabled: true
          priority: 4
          timeout: 10s
          retry_count: 2
          parameters:
            bank_code: "bank_code"
            account_number: "account_number"
          fallback: "stripe"
    notification_service:
      default_adapter: "email"
      adapters:
        email:
          enabled: true
          priority: 1
          timeout: 5s
          retry_count: 3
          parameters:
            smtp_host: "smtp.gmail.com"
            smtp_port: "587"
          fallback: "sms"
        sms:
          enabled: true
          priority: 2
          timeout: 3s
          retry_count: 3
          parameters:
            api_key: "sms_api_key"
          fallback: "push"
        push:
          enabled: true
          priority: 3
          timeout: 2s
          retry_count: 3
          parameters:
            api_key: "push_api_key"
          fallback: "webhook"
        webhook:
          enabled: true
          priority: 4
          timeout: 5s
          retry_count: 3
          parameters:
            webhook_url: "webhook_url"
          fallback: "slack"
        slack:
          enabled: true
          priority: 5
          timeout: 3s
          retry_count: 3
          parameters:
            webhook_url: "slack_webhook_url"
          fallback: "email"
    database:
      default_adapter: "mysql"
      adapters:
        mysql:
          enabled: true
          priority: 1
          timeout: 5s
          retry_count: 3
          parameters:
            host: "localhost:3306"
            username: "root"
            password: "password"
            database: "adapter_db"
          fallback: "postgresql"
        postgresql:
          enabled: true
          priority: 2
          timeout: 5s
          retry_count: 3
          parameters:
            host: "localhost:5432"
            username: "postgres"
            password: "password"
            database: "adapter_db"
          fallback: "mongodb"
        mongodb:
          enabled: true
          priority: 3
          timeout: 5s
          retry_count: 3
          parameters:
            uri: "mongodb://localhost:27017"
            database: "adapter_db"
          fallback: "mysql"

log_level: info
