server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "facade_db"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s

  mongodb:
    uri: "mongodb://localhost:27017"
    database: "facade_db"
    timeout: 30s
    max_pool_size: 100
    min_pool_size: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

kafka:
  brokers:
    - "localhost:9092"
  producer:
    retry_max: 3
    retry_backoff: 100ms
    required_acks: 1
    compression: "snappy"
  consumer:
    group_id: "facade-service"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    auto_commit_interval: 1s

services:
  payment:
    name: "payment-service"
    enabled: true
    url: "http://localhost:8081"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  notification:
    name: "notification-service"
    enabled: true
    url: "http://localhost:8082"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  user:
    name: "user-service"
    enabled: true
    url: "http://localhost:8083"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  order:
    name: "order-service"
    enabled: true
    url: "http://localhost:8084"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  inventory:
    name: "inventory-service"
    enabled: true
    url: "http://localhost:8085"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  analytics:
    name: "analytics-service"
    enabled: true
    url: "http://localhost:8086"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

  audit:
    name: "audit-service"
    enabled: true
    url: "http://localhost:8087"
    timeout: 30s
    retry_count: 3
    headers:
      "Content-Type": "application/json"
      "User-Agent": "facade-service"

facade:
  name: "ecommerce-facade"
  version: "1.0.0"
  description: "E-commerce facade service providing simplified interface to complex operations"
  timeout: 30s
  max_retries: 3
  retry_delay: 1s
  enable_compression: true
  enable_cors: true
  enable_metrics: true
  enable_tracing: false

cache:
  enabled: true
  type: "memory"
  ttl: 5m
  max_size: 1000
  cleanup_interval: 10m

message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "orders"
    - "payments"
    - "notifications"
    - "analytics"
    - "audit"

websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  max_message_size: 512

security:
  enabled: true
  jwt_secret: "your-secret-key-change-in-production"
  token_expiry: 24h
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 1m

monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false
    path: "logs/facade.log"
    max_size: 100
    max_backups: 3
    max_age: 28

health_check:
  enabled: true
  interval: 30s
  timeout: 5s
  retry_count: 3

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

api:
  version: "v1"
  prefix: "/api/v1"
  timeout: 30s
  max_request_size: 1048576  # 1MB
  enable_cors: true
  enable_compression: true
  enable_rate_limiting: true

business_logic:
  order_processing:
    enable_inventory_check: true
    enable_payment_processing: true
    enable_notifications: true
    enable_analytics: true
    enable_audit_logging: true
    timeout: 30s
    retry_count: 3

  user_dashboard:
    enable_order_history: true
    enable_payment_history: true
    enable_analytics: true
    enable_activity_log: true
    cache_ttl: 5m
    timeout: 10s

  notifications:
    enable_email: true
    enable_sms: true
    enable_push: true
    enable_bulk: true
    retry_count: 3
    retry_delay: 1s
    batch_size: 100

  system_health:
    enable_overall_health: true
    enable_service_health: true
    enable_system_metrics: true
    enable_service_metrics: true
    timeout: 5s
    interval: 30s
