server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 3306
  username: root
  password: password
  database: command_db
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

mongodb:
  uri: mongodb://localhost:27017
  database: command_db
  max_pool_size: 100
  min_pool_size: 10
  max_idle_time: 30m

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

kafka:
  brokers: ["localhost:9092"]
  topics:
    command_events: command-events
    command_metrics: command-metrics
  producer:
    batch_size: 100
    batch_timeout: 10ms
    compression: gzip
  consumer:
    group_id: command-service
    auto_offset_reset: earliest
    max_wait_time: 1s

command:
  max_retries: 3
  retry_delay: 1s
  timeout: 30s
  enable_auditing: true
  enable_metrics: true
  enable_validation: true
  enable_scheduling: true
  enable_queuing: true
  max_queue_size: 1000
  max_history_size: 10000
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30s
    half_open_max_calls: 3

log_level: info
