server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  host: localhost
  port: 3306
  user: root
  password: password
  dbname: singleton_db
  sslmode: disable
  max_conns: 100
  max_idle: 10

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

kafka:
  brokers:
    - localhost:9092
  topic: singleton-events
  group_id: singleton-service

mongodb:
  uri: mongodb://localhost:27017
  database: singleton_db
