server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "flyweight_db"
    charset: "utf8mb4"
    parse_time: true
    loc: "Local"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s

  mongodb:
    uri: "mongodb://localhost:27017"
    database: "flyweight_db"
    timeout: 30s
    max_pool_size: 100
    min_pool_size: 10

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

kafka:
  brokers:
    - "localhost:9092"
  producer:
    retry_max: 3
    retry_backoff: 100ms
    required_acks: 1
    compression: "snappy"
  consumer:
    group_id: "flyweight-service"
    auto_offset_reset: "earliest"
    enable_auto_commit: true
    auto_commit_interval: 1s

flyweight:
  name: "flyweight-service"
  version: "1.0.0"
  description: "Flyweight Pattern Implementation Service"
  max_size: 1000
  ttl: 5m
  cleanup_interval: 10m
  types:
    - "product"
    - "user"
    - "order"
    - "notification"
    - "configuration"

cache:
  enabled: true
  type: "memory"
  ttl: 5m
  max_size: 1000
  cleanup_interval: 10m

message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "flyweights"
    - "cache"
    - "notifications"
    - "analytics"
    - "audit"

websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s
  ping_period: 54s
  pong_wait: 60s
  max_message_size: 512

security:
  enabled: true
  jwt_secret: "your-secret-key-change-in-production"
  token_expiry: 24h
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 1m

monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    enabled: false
    path: "logs/flyweight.log"
    max_size: 100
    max_backups: 3
    max_age: 28

health_check:
  enabled: true
  interval: 30s
  timeout: 5s
  retry_count: 3

metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

api:
  version: "v1"
  prefix: "/api/v1"
  timeout: 30s
  max_request_size: 1048576  # 1MB
  enable_cors: true
  enable_compression: true
  enable_rate_limiting: true

business_logic:
  flyweight_management:
    enable_auto_cleanup: true
    enable_cache_warming: true
    enable_metrics_collection: true
    enable_health_checks: true
    timeout: 30s
    retry_count: 3

  data_retrieval:
    enable_database_fallback: true
    enable_cache_optimization: true
    enable_parallel_loading: true
    cache_ttl: 5m
    timeout: 10s

  factory_operations:
    enable_shared_flyweights: true
    enable_unshared_flyweights: true
    enable_type_validation: true
    enable_statistics: true
    max_flyweights: 1000

  performance:
    enable_connection_pooling: true
    enable_async_processing: true
    enable_compression: true
    enable_encryption: false
    batch_size: 100

  memory_management:
    enable_gc_optimization: true
    enable_memory_monitoring: true
    enable_cleanup_scheduling: true
    cleanup_threshold: 0.8
    max_memory_usage: 512MB
