server:
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: localhost
  port: 3306
  username: root
  password: password
  database: strategy_db
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: 1h

mongodb:
  uri: mongodb://localhost:27017
  database: strategy_db
  max_pool_size: 100
  min_pool_size: 10
  max_idle_time: 30m

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  min_idle_conns: 5

kafka:
  brokers: ["localhost:9092"]
  topics:
    strategy_events: strategy-events
    strategy_metrics: strategy-metrics
  producer:
    batch_size: 100
    batch_timeout: 10ms
    compression: gzip
  consumer:
    group_id: strategy-service
    auto_offset_reset: earliest
    max_wait_time: 1s

strategy:
  default_strategy: "stripe"
  fallback_strategy: "bank_transfer"
  timeout: 5s
  retry_count: 3
  circuit_breaker:
    enabled: true
    failure_threshold: 5
    recovery_timeout: 30s
    half_open_max_calls: 3
  strategies:
    stripe:
      enabled: true
      priority: 1
      timeout: 5s
      retry_count: 3
      parameters:
        api_key: "sk_test_..."
        webhook_secret: "whsec_..."
      fallback: "razorpay"
    razorpay:
      enabled: true
      priority: 2
      timeout: 5s
      retry_count: 3
      parameters:
        api_key: "rzp_test_..."
        api_secret: "rzp_test_..."
      fallback: "paypal"
    paypal:
      enabled: true
      priority: 3
      timeout: 5s
      retry_count: 3
      parameters:
        client_id: "paypal_client_id"
        client_secret: "paypal_client_secret"
      fallback: "bank_transfer"
    bank_transfer:
      enabled: true
      priority: 4
      timeout: 10s
      retry_count: 2
      parameters:
        bank_code: "bank_code"
        account_number: "account_number"
      fallback: "stripe"

log_level: info
