name: "Unit of Work Service"
version: "1.0.0"
description: "Unit of Work pattern implementation with microservice architecture"

max_entities: 10000
max_repositories: 100
transaction_timeout: 30s
cleanup_interval: 1h

validation_enabled: true
caching_enabled: true
monitoring_enabled: true
auditing_enabled: true

supported_entity_types:
  - "user"
  - "order"
  - "product"
  - "payment"
  - "custom"

default_entity_type: "custom"

validation_rules:
  max_name_length: 100
  max_description_length: 500

metadata:
  environment: "production"
  region: "us-east-1"

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "unit_of_work_db"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "unit_of_work_db"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

cache:
  enabled: true
  type: "memory"
  ttl: 5m
  max_size: 1000
  cleanup_interval: 10m

message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "unit-of-work-events"

websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s

security:
  enabled: true
  jwt_secret: "your-secret-key"
  token_expiry: 24h
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 1m

monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"
