[package]
name = "dsa_library"
version = "0.1.0"
edition = "2021"

[lib]
name = "dsa_library"
path = "src/lib.rs"

[dev-dependencies]
proptest = "1"
criterion = "0.5"

[[bench]]
name = "quicksort"
harness = false
