name: "Template Method Service"
version: "1.0.0"
description: "Template Method pattern implementation with microservice architecture"

max_template_methods: 1000
max_steps: 100
max_execution_time: 30m
max_retries: 3
retry_delay: 1s
retry_backoff: 2.0

validation_enabled: true
caching_enabled: true
monitoring_enabled: true
auditing_enabled: true
scheduling_enabled: true

supported_types:
  - "document_processing"
  - "data_validation"
  - "workflow"
  - "api_request"
  - "database_operation"

default_type: "workflow"

validation_rules:
  max_steps: 100
  max_execution_time: 30m
  max_retries: 3

metadata:
  environment: "production"
  region: "us-east-1"

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "password"
    database: "template_method_db"
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "template_method_db"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0

cache:
  enabled: true
  type: "memory"
  ttl: 5m
  max_size: 1000
  cleanup_interval: 10m

message_queue:
  enabled: true
  brokers:
    - "localhost:9092"
  topics:
    - "template-method-events"

websocket:
  enabled: true
  port: 8080
  read_buffer_size: 1024
  write_buffer_size: 1024
  handshake_timeout: 10s

security:
  enabled: true
  jwt_secret: "your-secret-key"
  token_expiry: 24h
  allowed_origins:
    - "*"
  rate_limit_enabled: true
  rate_limit_requests: 100
  rate_limit_window: 1m

monitoring:
  enabled: true
  port: 9090
  path: "/metrics"
  collect_interval: 30s

logging:
  level: "info"
  format: "json"
  output: "stdout"
